version: '3.5'

services:
        database:
                image: mysql/mysql-server:5.7
                container_name: mykabum
                ports:
                        - "3306:3306"
                expose:
                        - "3306"
                environment:
                        MYSQL_ROOT_PASSWORD: myKw15
                        MYSQL_DATABASE: kabum
                        MYSQL_USER: kabum
                        MYSQL_PASSWORD: n030N603y5qLf4497
                networks:
                        - kabum-network

        webserver:
                image: nginx:kabum
                container_name: webserver
                volumes:
                        - ./frontend/:/usr/share/nginx/html/
                        - ./backend/:/usr/lib/cgi-bin/sys/
                        - ./etc/nginx:/etc/nginx
                        - ./etc/credentials.pl:/etc/kabum/credentials.pl
                ports:
                        - "80:80"
                        - "443:443"
                networks:
                        - kabum-network

networks:
        kabum-network:
                driver: bridge
